# Generated by Django 5.0.6 on 2024-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
