# Generated by Django 5.0.6 on 2024-05-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscription_user_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='duration',
            new_name='token',
        ),
    ]
